BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Cities";
CREATE TABLE "Cities" (
	"cityID"	INTEGER,
	"name"	TEXT NOT NULL,
	"country"	TEXT NOT NULL,
	"country_code"	TEXT NOT NULL CHECK(LENGTH(country_code) = 2),
	"is_favourite"	INTEGER NOT NULL CHECK("is_favourite" BETWEEN 0 AND 1),
	PRIMARY KEY("cityID" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Weather";
CREATE TABLE "Weather" (
	"cityID"	INTEGER NOT NULL,
	"temp"	REAL NOT NULL,
	"feels_like"	REAL NOT NULL,
	"description"	TEXT NOT NULL,
	"humidity"	INTEGER NOT NULL CHECK("humidity" BETWEEN 0 AND 100),
	"wind_speed"	REAL NOT NULL,
	"offset"	INTEGER NOT NULL,
	"sunrise"	INTEGER NOT NULL,
	"sunset"	INTEGER NOT NULL,
	"tod"	VARCHAR(1) NOT NULL,
	PRIMARY KEY("cityID"),
	FOREIGN KEY("cityID") REFERENCES "Cities"("cityID") ON DELETE CASCADE
);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (1,'New York City','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (2,'Los Angeles','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (3,'Chicago','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (4,'Houston','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (5,'Phoenix','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (6,'Philadelphia','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (7,'San Antonio','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (8,'San Diego','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (9,'Dallas','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (10,'San Jose','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (11,'Austin','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (12,'Jacksonville','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (13,'Fort Worth','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (14,'Columbus','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (15,'Indianapolis','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (16,'Charlotte','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (17,'San Francisco','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (18,'Seattle','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (19,'Denver','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (20,'Washington D.C.','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (21,'Boston','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (22,'El Paso','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (23,'Nashville','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (24,'Detroit','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (25,'Oklahoma City','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (26,'Portland','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (27,'Las Vegas','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (28,'Memphis','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (29,'Louisville','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (30,'Baltimore','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (31,'Milwaukee','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (32,'Albuquerque','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (33,'Tucson','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (34,'Fresno','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (35,'Sacramento','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (36,'Kansas City','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (37,'Long Beach','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (38,'Mesa','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (39,'Atlanta','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (40,'Colorado Springs','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (41,'Virginia Beach','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (42,'Raleigh','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (43,'Omaha','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (44,'Miami','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (45,'Oakland','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (46,'Minneapolis','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (47,'Tulsa','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (48,'Wichita','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (49,'New Orleans','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (50,'Arlington','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (51,'Cleveland','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (52,'Bakersfield','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (53,'Tampa','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (54,'Aurora','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (55,'Honolulu','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (56,'Anaheim','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (57,'Santa Ana','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (58,'Corpus Christi','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (59,'Riverside','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (60,'Lexington','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (61,'St. Louis','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (62,'Stockton','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (63,'Pittsburgh','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (64,'St. Paul','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (65,'Cincinnati','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (66,'Anchorage','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (67,'Henderson','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (68,'Greensboro','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (69,'Plano','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (70,'Newark','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (71,'Lincoln','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (72,'Toledo','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (73,'Orlando','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (74,'Chula Vista','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (75,'Irvine','United States','US',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (76,'Toronto','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (77,'Montreal','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (78,'Vancouver','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (79,'Calgary','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (80,'Edmonton','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (81,'Ottawa','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (82,'Winnipeg','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (83,'Quebec City','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (84,'Kitchener','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (85,'Vienna','Austria','AT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (86,'Victoria','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (87,'Halifax','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (88,'Oshawa','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (89,'Windsor','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (90,'Saskatoon','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (91,'Regina','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (92,'St. John''s','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (93,'Barrie','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (94,'Kelowna','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (95,'Kingston','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (96,'Guelph','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (97,'Abbotsford','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (98,'Moncton','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (99,'Saint John','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (100,'Nanaimo','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (101,'Peterborough','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (102,'Red Deer','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (103,'Lethbridge','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (104,'Kamloops','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (105,'Saanich','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (106,'Medicine Hat','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (107,'Prince George','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (108,'Fredericton','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (109,'Trois-Rivières','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (110,'Chatham-Kent','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (111,'Saint-Jean-sur-Richelieu','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (112,'Saint-Jérôme','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (113,'Burnaby','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (114,'Coquitlam','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (115,'Brantford','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (116,'Sault Ste. Marie','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (117,'Prince Rupert','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (118,'Corner Brook','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (119,'Antwerp','Belgium','BE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (120,'Yellowknife','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (121,'Iqaluit','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (122,'Hamilton','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (123,'Mexico City','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (124,'Guadalajara','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (125,'Monterrey','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (126,'Puebla','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (127,'Tijuana','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (128,'Ciudad Juárez','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (129,'León','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (130,'Zapopan','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (131,'Nezahualcóyotl','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (132,'Mexicali','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (133,'Culiacán','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (134,'Mérida','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (135,'Cancún','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (136,'Aguascalientes','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (137,'Morelia','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (138,'Saltillo','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (139,'Reynosa','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (140,'Toluca','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (141,'Querétaro','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (142,'Torreón','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (143,'Ciudad Obregón','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (144,'Villahermosa','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (145,'San Luis Potosí','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (146,'Chihuahua','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (147,'Tlalnepantla','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (148,'Tuxtla Gutiérrez','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (149,'Chetumal','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (150,'Cuernavaca','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (151,'Veracruz','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (152,'Manzanillo','Mexico','MX',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (153,'London','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (154,'Paris','France','FR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (155,'Berlin','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (156,'Madrid','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (157,'Rome','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (158,'Amsterdam','Netherlands','NL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (159,'Brussels','Belgium','BE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (160,'Frankfurt','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (161,'Munich','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (162,'Barcelona','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (163,'Milan','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (164,'Zurich','Switzerland','CH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (165,'Geneva','Switzerland','CH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (166,'Whitehorse','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (167,'Dublin','Ireland','IE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (168,'Thunder Bay','Canada','CA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (169,'Copenhagen','Denmark','DK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (170,'Hamburg','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (171,'Rotterdam','Netherlands','NL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (172,'Düsseldorf','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (173,'Lille','France','FR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (174,'Lyon','France','FR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (175,'Marseille','France','FR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (176,'Tallinn','Estonia','EE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (177,'Cologne','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (178,'Basel','Switzerland','CH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (179,'Manchester','United Kingdom','GB',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (180,'Glasgow','United Kingdom','GB',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (181,'Stuttgart','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (182,'Hannover','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (183,'Bremen','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (184,'Luxembourg City','Luxembourg','LU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (185,'Bern','Switzerland','CH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (186,'Edinburgh','United Kingdom','GB',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (187,'Birmingham','United Kingdom','GB',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (188,'Nantes','France','FR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (189,'Leipzig','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (190,'Turin','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (191,'Palermo','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (192,'Dortmund','Germany','DE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (193,'Warsaw','Poland','PL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (194,'Prague','Czech Republic','CZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (195,'Budapest','Hungary','HU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (196,'Bucharest','Romania','RO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (197,'Sofia','Bulgaria','BG',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (198,'Belgrade','Serbia','RS',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (199,'Zagreb','Croatia','HR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (200,'Ljubljana','Slovenia','SI',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (201,'Bratislava','Slovakia','SK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (202,'Riga','Latvia','LV',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (203,'Vilnius','Lithuania','LT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (204,'Kyiv','Ukraine','UA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (205,'Minsk','Belarus','BY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (206,'Moscow','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (207,'Saint Petersburg','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (208,'Samara','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (209,'Novosibirsk','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (210,'Kazan','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (211,'Yekaterinburg','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (212,'Nizhny Novgorod','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (213,'Ufa','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (214,'Chelyabinsk','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (215,'Volgograd','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (216,'Rostov-on-Don','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (217,'Naples','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (218,'Hamilton','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (219,'Bologna','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (220,'Bari','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (221,'Florence','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (222,'Genoa','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (223,'Venice','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (224,'Oslo','Norway','NO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (225,'Porto','Portugal','PT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (226,'Malaga','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (227,'Murcia','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (228,'Alicante','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (229,'Split','Croatia','HR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (230,'Dubrovnik','Croatia','HR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (231,'Thessaloniki','Greece','GR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (232,'Catania','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (233,'Lecce','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (234,'Trieste','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (235,'Verona','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (236,'Salerno','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (237,'Taranto','Italy','IT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (238,'Lisbon','Portugal','PT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (239,'Singapore','Singapore','SG',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (240,'Helsinki','Finland','FI',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (241,'Reykjavik','Iceland','IS',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (242,'Valencia','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (243,'Seville','Spain','ES',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (244,'Gothenburg','Sweden','SE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (245,'Bergen','Norway','NO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (246,'Malmö','Sweden','SE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (247,'Aarhus','Denmark','DK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (248,'Uppsala','Sweden','SE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (249,'Turku','Finland','FI',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (250,'Aalborg','Denmark','DK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (251,'Tokyo','Japan','JP',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (252,'Beijing','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (253,'Shanghai','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (254,'Seoul','South Korea','KR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (255,'Taipei','Taiwan','TW',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (256,'Hong Kong','Hong Kong SAR','HK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (257,'Osaka','Japan','JP',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (258,'Guangzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (259,'Shenzhen','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (260,'Wuhan','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (261,'Chengdu','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (262,'Nanjing','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (263,'Chongqing','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (264,'Tianjin','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (265,'Xi''an','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (266,'Hangzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (267,'Dongguan','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (268,'Foshan','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (269,'Shenyang','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (270,'Harbin','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (271,'Suzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (272,'Qingdao','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (273,'Dalian','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (274,'Jinan','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (275,'Zhengzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (276,'Changchun','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (277,'Kunming','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (278,'Xiamen','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (279,'Fuzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (280,'Hefei','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (281,'Lanzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (282,'Urumqi','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (283,'Wuxi','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (284,'Yantai','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (285,'Ningbo','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (286,'Baotou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (287,'Quanzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (288,'Weifang','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (289,'Yangzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (290,'Zhuhai','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (291,'Nantong','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (292,'Taizhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (293,'Huaian','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (294,'Huzhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (295,'Yancheng','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (296,'Zhenjiang','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (297,'Jiaxing','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (298,'Huizhou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (299,'Jilin','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (300,'Yinchuan','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (301,'Hohhot','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (302,'Haikou','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (303,'Linyi','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (304,'Mianyang','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (305,'Fushun','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (306,'Jiaozuo','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (307,'Zaozhuang','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (308,'Xining','China','CN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (309,'Ulaanbaatar','Mongolia','MN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (310,'Mumbai','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (311,'Delhi','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (312,'Bangalore','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (313,'Hyderabad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (314,'Ahmedabad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (315,'Chennai','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (316,'Kolkata','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (317,'Surat','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (318,'Pune','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (319,'Jaipur','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (320,'Kanpur','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (321,'Lucknow','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (322,'Nagpur','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (323,'Indore','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (324,'Thane','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (325,'Bhopal','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (326,'Visakhapatnam','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (327,'Pimpri-Chinchwad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (328,'Patna','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (329,'Vadodara','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (330,'Ghaziabad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (331,'Ludhiana','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (332,'Agra','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (333,'Nashik','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (334,'Faridabad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (335,'Meerut','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (336,'Rajkot','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (337,'Kalyan-Dombivali','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (338,'Vasai-Virar','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (339,'Varanasi','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (340,'Srinagar','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (341,'Aurangabad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (342,'Dhanbad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (343,'Amritsar','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (344,'Navi Mumbai','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (345,'Allahabad','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (346,'Howrah','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (347,'Gwalior','India','IN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (348,'Colombo','Sri Lanka','LK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (349,'Karachi','Pakistan','PK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (350,'Lahore','Pakistan','PK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (351,'Dhaka','Bangladesh','BD',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (352,'Chittagong','Bangladesh','BD',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (353,'Kathmandu','Nepal','NP',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (354,'Thimphu','Bhutan','BT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (355,'Male','Maldives','MV',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (356,'Islamabad','Pakistan','PK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (357,'Rawalpindi','Pakistan','PK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (358,'Faisalabad','Pakistan','PK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (359,'Multan','Pakistan','PK',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (360,'Jakarta','Indonesia','ID',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (361,'Bangkok','Thailand','TH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (362,'Kuala Lumpur','Malaysia','MY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (363,'Stockholm','Sweden','SE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (364,'Manila','Philippines','PH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (365,'Ho Chi Minh City','Vietnam','VN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (366,'Hanoi','Vietnam','VN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (367,'Yangon','Myanmar','MM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (368,'Phnom Penh','Cambodia','KH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (369,'Surabaya','Indonesia','ID',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (370,'Medan','Indonesia','ID',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (371,'Makassar','Indonesia','ID',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (372,'Bandung','Indonesia','ID',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (373,'Batam','Indonesia','ID',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (374,'George Town','Malaysia','MY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (375,'Johor Bahru','Malaysia','MY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (376,'Penang','Malaysia','MY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (377,'Phuket','Thailand','TH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (378,'Chiang Mai','Thailand','TH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (379,'Nonthaburi','Thailand','TH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (380,'Chiang Rai','Thailand','TH',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (381,'Vientiane','Laos','LA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (382,'Mandalay','Myanmar','MM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (383,'Naypyidaw','Myanmar','MM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (384,'Da Nang','Vietnam','VN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (385,'Almaty','Kazakhstan','KZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (386,'Tashkent','Uzbekistan','UZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (387,'Ashgabat','Turkmenistan','TM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (388,'Bishkek','Kyrgyzstan','KG',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (389,'Dushanbe','Tajikistan','TJ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (390,'Istanbul','Turkey','TR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (391,'Dubai','United Arab Emirates','AE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (392,'Riyadh','Saudi Arabia','SA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (393,'Tehran','Iran','IR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (394,'Abu Dhabi','United Arab Emirates','AE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (395,'Sydney','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (396,'Melbourne','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (397,'Brisbane','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (398,'Perth','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (399,'Adelaide','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (400,'Gold Coast','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (401,'Canberra','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (402,'Newcastle','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (403,'Wollongong','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (404,'Logan City','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (405,'Hobart','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (406,'Geelong','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (407,'Townsville','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (408,'Cairns','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (409,'Toowoomba','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (410,'Darwin','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (411,'Ballarat','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (412,'Bendigo','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (413,'Albury','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (414,'Mackay','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (415,'Rockhampton','Australia','AU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (416,'Auckland','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (417,'Wellington','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (418,'Christchurch','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (419,'London','United Kingdom','GB',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (420,'Tauranga','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (421,'Dunedin','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (422,'Palmerston North','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (423,'Napier','New Zealand','NZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (424,'São Paulo','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (425,'Rio de Janeiro','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (426,'Brasília','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (427,'Salvador','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (428,'Fortaleza','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (429,'Belo Horizonte','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (430,'Manaus','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (431,'Curitiba','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (432,'Recife','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (433,'Porto Alegre','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (434,'Belém','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (435,'Goiânia','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (436,'Guarulhos','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (437,'Campinas','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (438,'São Luís','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (439,'São Gonçalo','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (440,'Maceió','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (441,'Duque de Caxias','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (442,'Natal','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (443,'Teresina','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (444,'Campo Grande','Brazil','BR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (445,'Buenos Aires','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (446,'Córdoba','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (447,'Rosario','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (448,'Mendoza','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (449,'La Plata','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (450,'San Miguel de Tucumán','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (451,'Mar del Plata','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (452,'Salta','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (453,'Santa Fe','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (454,'Bahía Blanca','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (455,'Resistencia','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (456,'Posadas','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (457,'San Juan','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (458,'Santiago del Estero','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (459,'San Salvador de Jujuy','Argentina','AR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (460,'Bogotá','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (461,'Medellín','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (462,'Cali','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (463,'Cartagena','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (464,'Barranquilla','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (465,'Bucaramanga','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (466,'Pereira','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (467,'Manizales','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (468,'Santa Marta','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (469,'Cúcuta','Colombia','CO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (470,'Santiago','Chile','CL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (471,'Valparaíso','Chile','CL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (472,'Concepción','Chile','CL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (473,'La Serena','Chile','CL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (474,'Temuco','Chile','CL',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (475,'Cairo','Egypt','EG',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (476,'Alexandria','Egypt','EG',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (477,'Casablanca','Morocco','MA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (478,'Rabat','Morocco','MA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (479,'Algiers','Algeria','DZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (480,'Tunis','Tunisia','TN',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (481,'Tripoli','Libya','LY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (482,'Luanda','Angola','AO',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (483,'Marrakech','Morocco','MA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (484,'Oran','Algeria','DZ',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (485,'San Salvador','El Salvador','SV',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (486,'Managua','Nicaragua','NI',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (487,'Panama City','Panama','PA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (488,'Doha','Qatar','QA',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (489,'Muscat','Oman','OM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (490,'Caracas','Venezuela','VE',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (491,'Asunción','Paraguay','PY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (492,'Montevideo','Uruguay','UY',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (493,'Kigali','Rwanda','RW',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (494,'Harare','Zimbabwe','ZW',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (495,'Lusaka','Zambia','ZM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (496,'Nouakchott','Mauritania','MR',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (497,'Port-au-Prince','Haiti','HT',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (498,'Kingston','Jamaica','JM',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (499,'Vladivostok','Russia','RU',0);
INSERT INTO "Cities" ("cityID","name","country","country_code","is_favourite") VALUES (500,'Bandar Seri Begawan','Brunei','BN',0);
DROP INDEX IF EXISTS "cities_favourite_idx";
CREATE INDEX "cities_favourite_idx" ON "Cities" (
	"is_favourite"
);
DROP INDEX IF EXISTS "cities_name_idx";
CREATE INDEX "cities_name_idx" ON "Cities" ("name");
COMMIT;
